num_rounds: 6
epochs_per_round: 15

num_classes: 5
class_names: ['class0','class1','class2','class3','class4']

fl_project_outputs_dir: FL_YOLOv8_Project_Outputs
device: cuda
clients:
  - model_name: client1
    data_yaml: path to client1/data.yaml
  - model_name: client2
    data_yaml: path to client2/data.yaml
  - model_name: client3
    data_yaml: path to client3/data.yaml
  - model_name: client4
    data_yaml: path to client4/data.yaml
